// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mess.proto

package protobuf;

public final class Mess {
  private Mess() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protobuf.Message.MessageType type = 1 [default = ERROR];</code>
     */
    boolean hasType();
    /**
     * <code>required .protobuf.Message.MessageType type = 1 [default = ERROR];</code>
     */
    protobuf.Mess.Message.MessageType getType();

    /**
     * <pre>
     * mess for CHAT
     * </pre>
     *
     * <code>optional string mess = 2;</code>
     */
    boolean hasMess();
    /**
     * <pre>
     * mess for CHAT
     * </pre>
     *
     * <code>optional string mess = 2;</code>
     */
    java.lang.String getMess();
    /**
     * <pre>
     * mess for CHAT
     * </pre>
     *
     * <code>optional string mess = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessBytes();

    /**
     * <pre>
     * id for SET_ID, CONNECT
     * </pre>
     *
     * <code>optional int64 id = 3;</code>
     */
    boolean hasId();
    /**
     * <pre>
     * id for SET_ID, CONNECT
     * </pre>
     *
     * <code>optional int64 id = 3;</code>
     */
    long getId();
  }
  /**
   * Protobuf type {@code protobuf.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      mess_ = "";
      id_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              protobuf.Mess.Message.MessageType value = protobuf.Mess.Message.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              mess_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              id_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.Mess.internal_static_protobuf_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.Mess.internal_static_protobuf_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.Mess.Message.class, protobuf.Mess.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code protobuf.Message.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ERROR = 0;</code>
       */
      ERROR(0),
      /**
       * <code>INFO = 1;</code>
       */
      INFO(1),
      /**
       * <code>SET_ID = 2;</code>
       */
      SET_ID(2),
      /**
       * <pre>
       * connect other client via id
       * </pre>
       *
       * <code>CONNECT = 3;</code>
       */
      CONNECT(3),
      /**
       * <code>DISCONNECT = 4;</code>
       */
      DISCONNECT(4),
      /**
       * <code>VIEW_SCREEN = 10;</code>
       */
      VIEW_SCREEN(10),
      /**
       * <code>SEND_FILE = 11;</code>
       */
      SEND_FILE(11),
      /**
       * <code>CHAT = 12;</code>
       */
      CHAT(12),
      ;

      /**
       * <code>ERROR = 0;</code>
       */
      public static final int ERROR_VALUE = 0;
      /**
       * <code>INFO = 1;</code>
       */
      public static final int INFO_VALUE = 1;
      /**
       * <code>SET_ID = 2;</code>
       */
      public static final int SET_ID_VALUE = 2;
      /**
       * <pre>
       * connect other client via id
       * </pre>
       *
       * <code>CONNECT = 3;</code>
       */
      public static final int CONNECT_VALUE = 3;
      /**
       * <code>DISCONNECT = 4;</code>
       */
      public static final int DISCONNECT_VALUE = 4;
      /**
       * <code>VIEW_SCREEN = 10;</code>
       */
      public static final int VIEW_SCREEN_VALUE = 10;
      /**
       * <code>SEND_FILE = 11;</code>
       */
      public static final int SEND_FILE_VALUE = 11;
      /**
       * <code>CHAT = 12;</code>
       */
      public static final int CHAT_VALUE = 12;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return ERROR;
          case 1: return INFO;
          case 2: return SET_ID;
          case 3: return CONNECT;
          case 4: return DISCONNECT;
          case 10: return VIEW_SCREEN;
          case 11: return SEND_FILE;
          case 12: return CHAT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.Mess.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Message.MessageType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .protobuf.Message.MessageType type = 1 [default = ERROR];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protobuf.Message.MessageType type = 1 [default = ERROR];</code>
     */
    public protobuf.Mess.Message.MessageType getType() {
      @SuppressWarnings("deprecation")
      protobuf.Mess.Message.MessageType result = protobuf.Mess.Message.MessageType.valueOf(type_);
      return result == null ? protobuf.Mess.Message.MessageType.ERROR : result;
    }

    public static final int MESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object mess_;
    /**
     * <pre>
     * mess for CHAT
     * </pre>
     *
     * <code>optional string mess = 2;</code>
     */
    public boolean hasMess() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * mess for CHAT
     * </pre>
     *
     * <code>optional string mess = 2;</code>
     */
    public java.lang.String getMess() {
      java.lang.Object ref = mess_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mess_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * mess for CHAT
     * </pre>
     *
     * <code>optional string mess = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessBytes() {
      java.lang.Object ref = mess_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mess_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private long id_;
    /**
     * <pre>
     * id for SET_ID, CONNECT
     * </pre>
     *
     * <code>optional int64 id = 3;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * id for SET_ID, CONNECT
     * </pre>
     *
     * <code>optional int64 id = 3;</code>
     */
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mess_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mess_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.Mess.Message)) {
        return super.equals(obj);
      }
      protobuf.Mess.Message other = (protobuf.Mess.Message) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasMess() == other.hasMess());
      if (hasMess()) {
        result = result && getMess()
            .equals(other.getMess());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasMess()) {
        hash = (37 * hash) + MESS_FIELD_NUMBER;
        hash = (53 * hash) + getMess().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.Mess.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.Mess.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.Mess.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.Mess.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.Mess.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.Mess.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.Mess.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.Mess.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.Mess.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.Mess.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.Mess.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.Mess.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.Mess.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Message)
        protobuf.Mess.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.Mess.internal_static_protobuf_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.Mess.internal_static_protobuf_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.Mess.Message.class, protobuf.Mess.Message.Builder.class);
      }

      // Construct using protobuf.Mess.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        mess_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.Mess.internal_static_protobuf_Message_descriptor;
      }

      @java.lang.Override
      public protobuf.Mess.Message getDefaultInstanceForType() {
        return protobuf.Mess.Message.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.Mess.Message build() {
        protobuf.Mess.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.Mess.Message buildPartial() {
        protobuf.Mess.Message result = new protobuf.Mess.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mess_ = mess_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.Mess.Message) {
          return mergeFrom((protobuf.Mess.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.Mess.Message other) {
        if (other == protobuf.Mess.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMess()) {
          bitField0_ |= 0x00000002;
          mess_ = other.mess_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.Mess.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.Mess.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .protobuf.Message.MessageType type = 1 [default = ERROR];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protobuf.Message.MessageType type = 1 [default = ERROR];</code>
       */
      public protobuf.Mess.Message.MessageType getType() {
        @SuppressWarnings("deprecation")
        protobuf.Mess.Message.MessageType result = protobuf.Mess.Message.MessageType.valueOf(type_);
        return result == null ? protobuf.Mess.Message.MessageType.ERROR : result;
      }
      /**
       * <code>required .protobuf.Message.MessageType type = 1 [default = ERROR];</code>
       */
      public Builder setType(protobuf.Mess.Message.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .protobuf.Message.MessageType type = 1 [default = ERROR];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mess_ = "";
      /**
       * <pre>
       * mess for CHAT
       * </pre>
       *
       * <code>optional string mess = 2;</code>
       */
      public boolean hasMess() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * mess for CHAT
       * </pre>
       *
       * <code>optional string mess = 2;</code>
       */
      public java.lang.String getMess() {
        java.lang.Object ref = mess_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mess_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * mess for CHAT
       * </pre>
       *
       * <code>optional string mess = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessBytes() {
        java.lang.Object ref = mess_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mess_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * mess for CHAT
       * </pre>
       *
       * <code>optional string mess = 2;</code>
       */
      public Builder setMess(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mess_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * mess for CHAT
       * </pre>
       *
       * <code>optional string mess = 2;</code>
       */
      public Builder clearMess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mess_ = getDefaultInstance().getMess();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * mess for CHAT
       * </pre>
       *
       * <code>optional string mess = 2;</code>
       */
      public Builder setMessBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mess_ = value;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       * id for SET_ID, CONNECT
       * </pre>
       *
       * <code>optional int64 id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * id for SET_ID, CONNECT
       * </pre>
       *
       * <code>optional int64 id = 3;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * id for SET_ID, CONNECT
       * </pre>
       *
       * <code>optional int64 id = 3;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * id for SET_ID, CONNECT
       * </pre>
       *
       * <code>optional int64 id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Message)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Message)
    private static final protobuf.Mess.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.Mess.Message();
    }

    public static protobuf.Mess.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.Mess.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmess.proto\022\010protobuf\"\316\001\n\007Message\0222\n\004ty" +
      "pe\030\001 \002(\0162\035.protobuf.Message.MessageType:" +
      "\005ERROR\022\014\n\004mess\030\002 \001(\t\022\n\n\002id\030\003 \001(\003\"u\n\013Mess" +
      "ageType\022\t\n\005ERROR\020\000\022\010\n\004INFO\020\001\022\n\n\006SET_ID\020\002" +
      "\022\013\n\007CONNECT\020\003\022\016\n\nDISCONNECT\020\004\022\017\n\013VIEW_SC" +
      "REEN\020\n\022\r\n\tSEND_FILE\020\013\022\010\n\004CHAT\020\014B\006B\004Mess"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Message_descriptor,
        new java.lang.String[] { "Type", "Mess", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
